### ISSUE TITLE
Test web3signer in Gnosis network

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DAppNodePackage-web3signer-gnosis#1]
**Test instructions**
You must have at least 2 Gnosis validators.

Install the web3signer gnosis and a client between [Prysm](https://github.com/dappnode/DAppNodePackage-Gnosis-Beacon-Chain-Prysm) and [Teku](https://github.com/dappnode/DAppNodePackage-teku-gnosis). You must get the hash from the Github latest release "dot".

In the client use the checkpoint sync feature to be able to start validating in minutes.

The web3signer will listen only to one client, you must select the client to listen to requests from at config.

For a deeper test, you may find it useful to check out the **metrics** from grafana dashboards from the client, web3signer, and docker host. Furthermore, in web3signer config, you can set the logs to **DEBUG** and get more details about whats going on

**Test report**

With an editable unique comment report any errors and feedback you may find necessary.

**Testers**
- @pablomendezroyo 
- @3alpha 
- @tropicar 
- @mgarciate

**Comment by tropicar** [comment]
Migration test (Installation of the first prysm version + web3signer, having keys on a previous prysm installation)
- No error in the installation of prysm and web3signer. 
- All my keys were added to the web3signer, and I could check it out in the web3signer UI.
- The web3signer with the prysm client keeps attesting

**Comment by alexpeterson91** [comment]
No errors encountered on 2 of my machines

**Comment by pablomendezroyo** [comment]
Done!
