### ISSUE TITLE
Add Consensus Client Lodestar in Gnosis Chain

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DAppNodePackage-web3signer-gnosis#28]
Develop the Lodestar package for Gnosis Chain and implement the Lodestar support in the web3signer gnosis.

Deppends on https://github.com/dappnode/DAppNodePackage-web3signer-prater/pull/62

**Comment by czepluch** [comment]
Is this done? I was trying to exit a validator using web3signer-gnosis with Lodestar and got the following error:
```
Status: Not exited ❌
Message: Error exiting validator PublishError.InsufficientPeersError posting (POST) voluntary exits to beaconchain. 
```
The validator has `0x01` credentials and I have 50 peers.

**Comment by dsimog01** [comment]
Hey @czepluch ! It looks like the config is actually included. This issue should have been closed, but let's move the discussion to https://github.com/dappnode/StakingBrain , which is where the logic related to your issue lives.
